### ISSUE TITLE
Create CSS file that uses local font sources

### ISSUE THREAD

**Issue by jeroensmink98** [CodeZombie/TypeRip#19]
It would be nice if the program could create a `.css` file with the local font definitions and their source.

Example:

```css
@font-face {
	font-family: "museo-slab";
	src: url("../fonts/museo-slab_300_italic.woff") format("woff"),url("museo-slab_300_italic.woff2") format("woff2"),url("museo-slab_300_italic.otf") format("opentype");
	font-display: auto;
	font-style: italic;
	font-weight: 300;
}
```

I'm currently [creating something like this](https://github.com/jeroensmink98/typekit-font-downloader) project but it works a little bit different and is a lot more buggier than your solution 

Therefore the requested enchantment
